### ISSUE TITLE
post 모델 place, status 필드 관련

### ISSUE THREAD

**Issue by 9ummy** [swsnu/swpp2021-team6#12]
1. `place` 필드
기존 `post` 모델에 `place`, `latitude`, `longitude` 필드가 있는데 
`place: {name: string, latitude: number, longitude: number, address: string, telephone: number}`
이렇게 장소에 대한 정보를 추가할 수 있을까요~~

2. `status` 필드
`boolean` 타입으로 넘겨주시면 표시할 때 더 편할 것 같습니다!

**Comment by kyungwon-lee** [comment]
넵! 반영해서 해결했습니다!
자세한 http data format은 notion이나 wiki page를 참고해주세요 :)
