### ISSUE TITLE
GET /posts/ response 정보

### ISSUE THREAD

**Issue by 9ummy** [swsnu/swpp2021-team6#13]
- `GET /posts/` 에 `post_id` 추가해주세요!
- `host` 는 호스트 유저의 `host_id`가 담기는 건가요?? `username` 문자열로 받아도 될 것 같아요
- `capacity`는 `post`의 `max_capacity` 오는 거 맞나요?
- `POST /posts/` 시에는 따로 response 없어도 될 것 같아요!

**Comment by 9ummy** [comment]
post 하고 생성된 post 정보 get post by id 할 때처럼 넘겨주세요!

**Comment by 9ummy** [comment]
그리구 GET /posts/ 할 때랑 GET /posts/<post_id> 할 때 넘어오는 post 정보 똑같아야 할 것 같습니다!
리스트다 아니다 차이만 있고?

**Comment by kyungwon-lee** [comment]
네네! 모두 backend에 반영했습니다.
자세한 json data format은 notion 페이지 or Wiki page를 참고해주세요!
