### ISSUE TITLE
POST /users/signin에  response body 형식 요청드립니다

### ISSUE THREAD

**Issue by SunnyBaik** [swsnu/swpp2021-team6#25]
아래와 같이 부탁드려요!
{
  "id": string;
  "nickname": string;
  "latitude": number;
  "longitude": number;
  "gu": string;
  "dong": string;
  "gender": string;
}

**Comment by kyungwon-lee** [comment]
넵! "id"를 "user_id" 이렇게 rename 해서 response body에 추가했습니다!
